version: '2'
services:
    samplecompanyapplication-app:
        image: samplecompanyapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@samplecompanyapplication-oracle:1521:sampleCompanyApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
